name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Get version
      run: ./dobo version
    - name: Shellcheck
      run: shellcheck ./dobo tests/test.sh
    - name: Run test
      run: ./tests/test.sh

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: .\dobo.bat version
