name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker login
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
      - name: Build
        run: docker build . -t ghcr.io/KeisukeYamashita/dobo 
      - name: Push
        run: docker push ghcr.io/KeisukeYamashita/dobo
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_GITHUB_TOKEN }}
